action update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,5 +18,9 @@ jobs:
       - name: Run tests
         run: |
           echo npm test
-          python main.py
-          exit 1
+          if [ $? -ne 0 ]; then
+            echo "fail"
+            exit 1
+          fi
+          
+          echo "success"
